[package]
name = "search-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
tantivy = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"
actix-web = "4"
tokio = { version = "1", features = ["full"] }
env_logger = "0.11"
log = "0.4"
